default: &default
  encoding: utf8
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: postgres:///development
  username: postgres

test:
  <<: *default
  database: postgres:///test
  username: postgres

production:
  <<: *default
  # url: <%= ENV.fetch("DATABASE_URL") %>
  # This happens automatically since Rails 4.1
